Simplify the code
electron/electron-quick-start pull request #617
Opened 2022-06-21 13:12 UTC by boubkhaled

Use textContent instead of innerText

2022-07-01 03:04 UTC, EtheWallet reviewed
f2cbf3a6b8b731ca76f68154783f2c7c977a11da2165ff2c21eca5e43f00f56c

2022-09-07 22:55 UTC, erickzhao requested changes

2022-09-07 22:55 UTC, erickzhao commented on preload.js
> +    document.getElementById(`${type}-version`)?.textContent = process.versions[type];
```
SyntaxError: Unexpected token '?.'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1074:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
```

2023-02-06 11:39 UTC, codebytere commented
Closing as this seems to have been abandoned.

2023-02-06 11:39 UTC, closed without merging